-- MySQL Script generated by MySQL Workbench
-- Mon Oct 12 13:01:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema modelosistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelosistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelosistema` DEFAULT CHARACTER SET utf8 ;
USE `modelosistema` ;

CREATE TABLE `anticipos` (
  `idAnticipos` int(11) NOT NULL AUTO_INCREMENT,
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  `descripcion_anticipo` varchar(45) DEFAULT NULL,
  `fecha_anticipo` date DEFAULT NULL,
  `monto_anticipo` double DEFAULT NULL,
  `estado_anticipo` binary(1) DEFAULT NULL,
  PRIMARY KEY (`idAnticipos`,`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Anticipos_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  CONSTRAINT `fk_Anticipos_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `area` (
  `idArea` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_area` varchar(45) NOT NULL,
  `Sucursal_idSucursal` int(11) NOT NULL,
  PRIMARY KEY (`idArea`),
  KEY `fk_Area_Sucursal1_idx` (`Sucursal_idSucursal`),
  CONSTRAINT `fk_Area_Sucursal1` FOREIGN KEY (`Sucursal_idSucursal`) REFERENCES `sucursal` (`idSucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `bono` (
  `idBono` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion` varchar(100) NOT NULL,
  `fecha_bono` date DEFAULT NULL,
  `monto` double NOT NULL,
  PRIMARY KEY (`idBono`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `cargo` (
  `idCargo` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_cargo` varchar(100) NOT NULL,
  `nombre_cargo` varchar(50) NOT NULL,
  `sueldo_base` double DEFAULT NULL,
  PRIMARY KEY (`idCargo`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE `cargo_x_empleado` (
  `Cargo_idCargo` int(11) NOT NULL,
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  `fecha_nombramiento` date NOT NULL,
  `fecha_fin` date DEFAULT NULL,
  PRIMARY KEY (`Cargo_idCargo`,`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Cargo_has_Empleado_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Cargo_has_Empleado_Cargo1_idx` (`Cargo_idCargo`),
  CONSTRAINT `fk_Cargo_has_Empleado_Cargo1` FOREIGN KEY (`Cargo_idCargo`) REFERENCES `cargo` (`idCargo`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_Cargo_has_Empleado_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ciudad` (
  `idCiudad` int(11) NOT NULL AUTO_INCREMENT,
  `nom_ciudad` varchar(100) NOT NULL,
  `Departamento_idDepartamento` int(11) NOT NULL,
  PRIMARY KEY (`idCiudad`,`Departamento_idDepartamento`),
  KEY `fk_Ciudad_Departamento1_idx` (`Departamento_idDepartamento`),
  CONSTRAINT `fk_Ciudad_Departamento1` FOREIGN KEY (`Departamento_idDepartamento`) REFERENCES `departamento` (`idDepartamento`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `cliente` (
  `idCliente` int(11) NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` int(11) NOT NULL,
  `fechaRegistro` date NOT NULL,
  PRIMARY KEY (`idCliente`,`Persona_idPersona`),
  UNIQUE KEY `Persona_idPersona_UNIQUE` (`Persona_idPersona`),
  KEY `fk_Cliente_Persona_idx` (`Persona_idPersona`),
  CONSTRAINT `fk_Cliente_Persona` FOREIGN KEY (`Persona_idPersona`) REFERENCES `persona` (`idPersona`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=211 DEFAULT CHARSET=utf8;

CREATE TABLE `compania` (
  `idCompania` int(11) NOT NULL AUTO_INCREMENT,
  `Telefono_idTelefono` int(11) NOT NULL,
  `Telefono_Persona_idPersona` int(11) NOT NULL,
  `nombre_compania` varchar(45) NOT NULL,
  PRIMARY KEY (`idCompania`,`Telefono_idTelefono`,`Telefono_Persona_idPersona`),
  KEY `fk_Compania_Telefono1_idx` (`Telefono_idTelefono`,`Telefono_Persona_idPersona`),
  CONSTRAINT `fk_Compania_Telefono1` FOREIGN KEY (`Telefono_idTelefono`, `Telefono_Persona_idPersona`) REFERENCES `telefono` (`idTelefono`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `contenedor` (
  `idContenedor` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_cont` varchar(45) NOT NULL,
  `TipoContenedor_idTipoContenedor` int(11) NOT NULL,
  PRIMARY KEY (`idContenedor`),
  KEY `fk_Contenedor_TipoContenedor1_idx` (`TipoContenedor_idTipoContenedor`),
  CONSTRAINT `fk_Contenedor_TipoContenedor1` FOREIGN KEY (`TipoContenedor_idTipoContenedor`) REFERENCES `tipocontenedor` (`idTipoContenedor`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `contrato` (
  `idContrato` int(11) NOT NULL AUTO_INCREMENT,
  `fechainicio_contrato` date NOT NULL,
  `fechafin_contrato` date NOT NULL,
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  `TipoContrato_idTipoContrato` int(11) NOT NULL,
  PRIMARY KEY (`idContrato`,`Empleado_idEmpleado`,`Empleado_Persona_idPersona`,`TipoContrato_idTipoContrato`),
  KEY `fk_Contrato_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Contrato_TipoContrato1_idx` (`TipoContrato_idTipoContrato`),
  CONSTRAINT `fk_Contrato_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_TipoContrato1` FOREIGN KEY (`TipoContrato_idTipoContrato`) REFERENCES `tipocontrato` (`idTipoContrato`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `correo` (
  `idCorreo` int(11) NOT NULL AUTO_INCREMENT,
  `dir_correo` varchar(45) NOT NULL,
  `Persona_idPersona` int(11) NOT NULL,
  PRIMARY KEY (`idCorreo`,`Persona_idPersona`),
  KEY `fk_Correo_Persona1_idx` (`Persona_idPersona`),
  CONSTRAINT `fk_Correo_Persona1` FOREIGN KEY (`Persona_idPersona`) REFERENCES `persona` (`idPersona`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=421 DEFAULT CHARSET=utf8;

CREATE TABLE `deduccion` (
  `idDeduccion` int(11) NOT NULL AUTO_INCREMENT,
  `fechainicio` date DEFAULT NULL,
  `fechafin` date DEFAULT NULL,
  `valor` double DEFAULT NULL,
  `TipoDeduccion_idTipoDeduccion` int(11) NOT NULL,
  PRIMARY KEY (`idDeduccion`,`TipoDeduccion_idTipoDeduccion`),
  KEY `fk_Deduccion_TipoDeduccion1_idx` (`TipoDeduccion_idTipoDeduccion`),
  CONSTRAINT `fk_Deduccion_TipoDeduccion1` FOREIGN KEY (`TipoDeduccion_idTipoDeduccion`) REFERENCES `tipodeduccion` (`idTipoDeduccion`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `departamento` (
  `idDepartamento` int(11) NOT NULL AUTO_INCREMENT,
  `nom_departamento` varchar(100) NOT NULL,
  `Pais_idPais` int(11) NOT NULL,
  PRIMARY KEY (`idDepartamento`,`Pais_idPais`),
  KEY `fk_Departamento_Pais1_idx` (`Pais_idPais`),
  CONSTRAINT `fk_Departamento_Pais1` FOREIGN KEY (`Pais_idPais`) REFERENCES `pais` (`idPais`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `empleado` (
  `idEmpleado` int(11) NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` int(11) NOT NULL,
  `sueldo_emp` double NOT NULL,
  PRIMARY KEY (`idEmpleado`,`Persona_idPersona`),
  KEY `fk_Empleado_Persona1_idx` (`Persona_idPersona`),
  CONSTRAINT `fk_Empleado_Persona1` FOREIGN KEY (`Persona_idPersona`) REFERENCES `persona` (`idPersona`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

CREATE TABLE `empleado_x_bono` (
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  `Bono_idBono` int(11) NOT NULL,
  `estado_bono` binary(1) DEFAULT NULL,
  `Planilla_idPlanilla` int(11) DEFAULT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`,`Bono_idBono`),
  KEY `fk_Empleado_has_Bono_Bono1_idx` (`Bono_idBono`),
  KEY `fk_Empleado_has_Bono_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Empleado_has_Bono_Planilla1_idx` (`Planilla_idPlanilla`),
  CONSTRAINT `fk_Empleado_has_Bono_Bono1` FOREIGN KEY (`Bono_idBono`) REFERENCES `bono` (`idBono`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Bono_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Bono_Planilla1` FOREIGN KEY (`Planilla_idPlanilla`) REFERENCES `planilla` (`idPlanilla`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `empleado_x_deduccion` (
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  `Deduccion_idDeduccion` int(11) NOT NULL,
  `fecha_emp_deduc` date NOT NULL,
  `estado_emp_deduc` binary(1) DEFAULT NULL,
  `Planilla_idPlanilla` int(11) DEFAULT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`,`Deduccion_idDeduccion`),
  KEY `fk_Empleado_has_Deduccion_Deduccion1_idx` (`Deduccion_idDeduccion`),
  KEY `fk_Empleado_has_Deduccion_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Empleado_x_Deduccion_Planilla1_idx` (`Planilla_idPlanilla`),
  CONSTRAINT `fk_Empleado_has_Deduccion_Deduccion1` FOREIGN KEY (`Deduccion_idDeduccion`) REFERENCES `deduccion` (`idDeduccion`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Deduccion_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_x_Deduccion_Planilla1` FOREIGN KEY (`Planilla_idPlanilla`) REFERENCES `planilla` (`idPlanilla`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `empleado_x_planilla` (
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  `Planilla_idPlanilla` int(11) NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`,`Planilla_idPlanilla`),
  KEY `fk_Empleado_has_Planilla_Planilla1_idx` (`Planilla_idPlanilla`),
  KEY `fk_Empleado_has_Planilla_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  CONSTRAINT `fk_Empleado_has_Planilla_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Planilla_Planilla1` FOREIGN KEY (`Planilla_idPlanilla`) REFERENCES `planilla` (`idPlanilla`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `factura_encabezado` (
  `idFactura` int(11) NOT NULL AUTO_INCREMENT,
  `fecha_factura` date NOT NULL,
  `observaciones` varchar(100) NOT NULL,
  `total_factura` double NOT NULL,
  `RTN` varchar(45) DEFAULT NULL,
  `Cliente_idCliente` int(11) NOT NULL,
  `Cliente_Persona_idPersona` int(11) NOT NULL,
  PRIMARY KEY (`idFactura`,`Cliente_idCliente`,`Cliente_Persona_idPersona`),
  KEY `fk_Factura_Encabezado_Cliente1_idx` (`Cliente_idCliente`,`Cliente_Persona_idPersona`),
  CONSTRAINT `fk_Factura_Encabezado_Cliente1` FOREIGN KEY (`Cliente_idCliente`, `Cliente_Persona_idPersona`) REFERENCES `cliente` (`idCliente`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `facturaencabezado_x_formapago` (
  `Factura_Encabezado_idFactura` int(11) NOT NULL,
  `Factura_Encabezado_Cliente_idCliente` int(11) NOT NULL,
  `Factura_Encabezado_Cliente_Persona_idPersona` int(11) NOT NULL,
  `FormaPago_idFormaPago` int(11) NOT NULL,
  `montoPagado` double NOT NULL,
  PRIMARY KEY (`Factura_Encabezado_idFactura`,`Factura_Encabezado_Cliente_idCliente`,`Factura_Encabezado_Cliente_Persona_idPersona`,`FormaPago_idFormaPago`),
  KEY `fk_Factura_Encabezado_has_FormaPago_FormaPago1_idx` (`FormaPago_idFormaPago`),
  KEY `fk_Factura_Encabezado_has_FormaPago_Factura_Encabezado1_idx` (`Factura_Encabezado_idFactura`,`Factura_Encabezado_Cliente_idCliente`,`Factura_Encabezado_Cliente_Persona_idPersona`),
  CONSTRAINT `fk_Factura_Encabezado_has_FormaPago_Factura_Encabezado1` FOREIGN KEY (`Factura_Encabezado_idFactura`, `Factura_Encabezado_Cliente_idCliente`, `Factura_Encabezado_Cliente_Persona_idPersona`) REFERENCES `factura_encabezado` (`idFactura`, `Cliente_idCliente`, `Cliente_Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Encabezado_has_FormaPago_FormaPago1` FOREIGN KEY (`FormaPago_idFormaPago`) REFERENCES `formapago` (`idFormaPago`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `facturaencabezado_x_producto` (
  `Factura_Encabezado_idFactura` int(11) NOT NULL,
  `Factura_Encabezado_Cliente_idCliente` int(11) NOT NULL,
  `Factura_Encabezado_Cliente_Persona_idPersona` int(11) NOT NULL,
  `Producto_idProducto` int(11) NOT NULL,
  `cantidadcompra` double NOT NULL,
  PRIMARY KEY (`Factura_Encabezado_idFactura`,`Factura_Encabezado_Cliente_idCliente`,`Factura_Encabezado_Cliente_Persona_idPersona`,`Producto_idProducto`),
  KEY `fk_Factura_Encabezado_has_Producto_Producto1_idx` (`Producto_idProducto`),
  KEY `fk_Factura_Encabezado_has_Producto_Factura_Encabezado1_idx` (`Factura_Encabezado_idFactura`,`Factura_Encabezado_Cliente_idCliente`,`Factura_Encabezado_Cliente_Persona_idPersona`),
  CONSTRAINT `fk_Factura_Encabezado_has_Producto_Factura_Encabezado1` FOREIGN KEY (`Factura_Encabezado_idFactura`, `Factura_Encabezado_Cliente_idCliente`, `Factura_Encabezado_Cliente_Persona_idPersona`) REFERENCES `factura_encabezado` (`idFactura`, `Cliente_idCliente`, `Cliente_Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Encabezado_has_Producto_Producto1` FOREIGN KEY (`Producto_idProducto`) REFERENCES `producto` (`idProducto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `formapago` (
  `idFormaPago` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_formapago` varchar(45) NOT NULL,
  PRIMARY KEY (`idFormaPago`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `jornada` (
  `idJornada` int(11) NOT NULL AUTO_INCREMENT,
  `horainicio_jor` datetime NOT NULL,
  `horafin_jor` datetime NOT NULL,
  `Empleado_idEmpleado` int(11) NOT NULL,
  `Empleado_Persona_idPersona` int(11) NOT NULL,
  PRIMARY KEY (`idJornada`,`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  KEY `fk_Jornada_Empleado1_idx` (`Empleado_idEmpleado`,`Empleado_Persona_idPersona`),
  CONSTRAINT `fk_Jornada_Empleado1` FOREIGN KEY (`Empleado_idEmpleado`, `Empleado_Persona_idPersona`) REFERENCES `empleado` (`idEmpleado`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `marca` (
  `idMarca` int(11) NOT NULL,
  `nombre_marca` varchar(45) NOT NULL,
  `descp_marca` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idMarca`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `movimiento` (
  `idMovimiento` int(11) NOT NULL AUTO_INCREMENT,
  `fechaTransaccion` date NOT NULL,
  `tipoMovimiento` varchar(1) NOT NULL,
  `cantidadPuntos` int(11) NOT NULL,
  `TarjetaAcumulacion_idTarjetaAcumulacion` int(11) NOT NULL,
  `TarjetaAcumulacion_Cliente_idCliente` int(11) NOT NULL,
  `TarjetaAcumulacion_Cliente_Persona_idPersona` int(11) NOT NULL,
  PRIMARY KEY (`idMovimiento`,`TarjetaAcumulacion_idTarjetaAcumulacion`,`TarjetaAcumulacion_Cliente_idCliente`,`TarjetaAcumulacion_Cliente_Persona_idPersona`),
  KEY `fk_Movimiento_TarjetaAcumulacion1_idx` (`TarjetaAcumulacion_idTarjetaAcumulacion`,`TarjetaAcumulacion_Cliente_idCliente`,`TarjetaAcumulacion_Cliente_Persona_idPersona`),
  CONSTRAINT `fk_Movimiento_TarjetaAcumulacion1` FOREIGN KEY (`TarjetaAcumulacion_idTarjetaAcumulacion`, `TarjetaAcumulacion_Cliente_idCliente`, `TarjetaAcumulacion_Cliente_Persona_idPersona`) REFERENCES `tarjetaacumulacion` (`idTarjetaAcumulacion`, `Cliente_idCliente`, `Cliente_Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pais` (
  `idPais` int(11) NOT NULL AUTO_INCREMENT,
  `nom_pais` varchar(100) NOT NULL,
  PRIMARY KEY (`idPais`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `pasillo` (
  `idPasillo` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_pasillo` varchar(45) NOT NULL,
  `Area_idArea` int(11) NOT NULL,
  PRIMARY KEY (`idPasillo`),
  KEY `fk_Pasillo_Area1_idx` (`Area_idArea`),
  CONSTRAINT `fk_Pasillo_Area1` FOREIGN KEY (`Area_idArea`) REFERENCES `area` (`idArea`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `pasillo_x_contenedor` (
  `Pasillo_idPasillo` int(11) NOT NULL,
  `Contenedor_idContenedor` int(11) NOT NULL,
  PRIMARY KEY (`Pasillo_idPasillo`,`Contenedor_idContenedor`),
  KEY `fk_Pasillo_has_Contenedor_Contenedor1_idx` (`Contenedor_idContenedor`),
  KEY `fk_Pasillo_has_Contenedor_Pasillo1_idx` (`Pasillo_idPasillo`),
  CONSTRAINT `fk_Pasillo_has_Contenedor_Contenedor1` FOREIGN KEY (`Contenedor_idContenedor`) REFERENCES `contenedor` (`idContenedor`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasillo_has_Contenedor_Pasillo1` FOREIGN KEY (`Pasillo_idPasillo`) REFERENCES `pasillo` (`idPasillo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `persona` (
  `idPersona` int(11) NOT NULL AUTO_INCREMENT,
  `Ciudad_idCiudad` int(11) DEFAULT '0',
  `Ciudad_Departamento_idDepartamento` int(11) DEFAULT '0',
  `pnombre` varchar(45) NOT NULL,
  `snombre` varchar(45) DEFAULT NULL,
  `papellido` varchar(45) NOT NULL,
  `sapellido` varchar(45) DEFAULT NULL,
  `num_identidad` varchar(45) DEFAULT NULL,
  `direccion` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE KEY `num_identidad_UNIQUE` (`num_identidad`),
  KEY `fk_Persona_Ciudad1_idx` (`Ciudad_idCiudad`,`Ciudad_Departamento_idDepartamento`),
  CONSTRAINT `fk_Persona_Ciudad1` FOREIGN KEY (`Ciudad_idCiudad`, `Ciudad_Departamento_idDepartamento`) REFERENCES `ciudad` (`idCiudad`, `Departamento_idDepartamento`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=261 DEFAULT CHARSET=utf8;

CREATE TABLE `planilla` (
  `idPlanilla` int(11) NOT NULL AUTO_INCREMENT,
  `fechaefectiva` date DEFAULT NULL,
  `fechainicio` date DEFAULT NULL,
  `fechafin` date DEFAULT NULL,
  `estado_planilla` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`idPlanilla`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `producto` (
  `idProducto` int(11) NOT NULL AUTO_INCREMENT,
  `descp_gral` varchar(1000) NOT NULL,
  `barcode` varchar(20) DEFAULT NULL,
  `precioCosto` double NOT NULL,
  `precioVenta` double NOT NULL,
  `porcentaje_desc` double DEFAULT NULL,
  `estado_producto` varchar(1) NOT NULL,
  `cantidad` double NOT NULL,
  `Contenedor_idContenedor` int(11) NOT NULL,
  `idTipoProducto` int(11) DEFAULT NULL,
  `idMarca` int(11) DEFAULT NULL,
  PRIMARY KEY (`idProducto`),
  KEY `fk_Producto_Contenedor1_idx` (`Contenedor_idContenedor`),
  KEY `fk_Producto_TipoProducto` (`idTipoProducto`),
  KEY `FK_MarcaProducto` (`idMarca`),
  CONSTRAINT `FK_MarcaProducto` FOREIGN KEY (`idMarca`) REFERENCES `marca` (`idMarca`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_Producto_Contenedor1` FOREIGN KEY (`Contenedor_idContenedor`) REFERENCES `contenedor` (`idContenedor`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_Producto_TipoProducto` FOREIGN KEY (`idTipoProducto`) REFERENCES `tipoproducto` (`idTipo_Producto`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE `producto_x_proveedor` (
  `Producto_idProducto` int(11) NOT NULL,
  `Proveedor_idProveedor` int(11) NOT NULL,
  `cantidad_ingreso` double NOT NULL,
  `fecha_ingreso` date NOT NULL,
  PRIMARY KEY (`Producto_idProducto`,`Proveedor_idProveedor`),
  KEY `fk_Producto_has_Proveedor_Proveedor1_idx` (`Proveedor_idProveedor`),
  KEY `fk_Producto_has_Proveedor_Producto1_idx` (`Producto_idProducto`),
  CONSTRAINT `fk_Producto_has_Proveedor_Producto1` FOREIGN KEY (`Producto_idProducto`) REFERENCES `producto` (`idProducto`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Proveedor_Proveedor1` FOREIGN KEY (`Proveedor_idProveedor`) REFERENCES `proveedor` (`idProveedor`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `proveedor` (
  `idProveedor` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` varchar(45) NOT NULL,
  `direccion_proveedor` varchar(45) NOT NULL,
  `telefono_proveedor` varchar(45) NOT NULL,
  `correo_proveedor` varchar(45) DEFAULT NULL,
  `Persona_idPersona` int(11) DEFAULT NULL,
  PRIMARY KEY (`idProveedor`),
  KEY `fk_Proveedor_Persona1_idx` (`Persona_idPersona`),
  CONSTRAINT `fk_Proveedor_Persona1` FOREIGN KEY (`Persona_idPersona`) REFERENCES `persona` (`idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8;

CREATE TABLE `sucursal` (
  `idSucursal` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_sucursal` varchar(45) NOT NULL,
  `direccion` varchar(45) NOT NULL,
  `Ciudad_idCiudad` int(11) NOT NULL,
  `Ciudad_Departamento_idDepartamento` int(11) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  KEY `fk_Sucursal_Ciudad1_idx` (`Ciudad_idCiudad`,`Ciudad_Departamento_idDepartamento`),
  CONSTRAINT `fk_Sucursal_Ciudad1` FOREIGN KEY (`Ciudad_idCiudad`, `Ciudad_Departamento_idDepartamento`) REFERENCES `ciudad` (`idCiudad`, `Departamento_idDepartamento`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `tarjetaacumulacion` (
  `idTarjetaAcumulacion` int(11) NOT NULL AUTO_INCREMENT,
  `fechaEmision` date NOT NULL,
  `fechaVencimiento` date NOT NULL,
  `Cliente_idCliente` int(11) NOT NULL,
  `Cliente_Persona_idPersona` int(11) NOT NULL,
  PRIMARY KEY (`idTarjetaAcumulacion`,`Cliente_idCliente`,`Cliente_Persona_idPersona`),
  KEY `fk_TarjetaAcumulacion_Cliente1_idx` (`Cliente_idCliente`,`Cliente_Persona_idPersona`),
  CONSTRAINT `fk_TarjetaAcumulacion_Cliente1` FOREIGN KEY (`Cliente_idCliente`, `Cliente_Persona_idPersona`) REFERENCES `cliente` (`idCliente`, `Persona_idPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `telefono` (
  `idTelefono` int(11) NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` int(11) NOT NULL,
  `num_telefono` varchar(45) NOT NULL,
  PRIMARY KEY (`idTelefono`,`Persona_idPersona`),
  KEY `fk_Telefono_Persona1_idx` (`Persona_idPersona`),
  CONSTRAINT `fk_Telefono_Persona1` FOREIGN KEY (`Persona_idPersona`) REFERENCES `persona` (`idPersona`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8;

CREATE TABLE `tipocontenedor` (
  `idTipoContenedor` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_tipocont` varchar(45) NOT NULL,
  PRIMARY KEY (`idTipoContenedor`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `tipocontrato` (
  `idTipoContrato` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_tipocon` varchar(100) NOT NULL,
  PRIMARY KEY (`idTipoContrato`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `tipodeduccion` (
  `idTipoDeduccion` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion` varchar(100) NOT NULL,
  `monto` double DEFAULT NULL,
  PRIMARY KEY (`idTipoDeduccion`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `tipoproducto` (
  `idTipo_Producto` int(11) NOT NULL AUTO_INCREMENT,
  `descp_tipo` varchar(50) NOT NULL,
  PRIMARY KEY (`idTipo_Producto`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `tipousuario` (
  `idtipousuario` int(11) NOT NULL AUTO_INCREMENT,
  `tipo` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`idtipousuario`),
  UNIQUE KEY `tipo_UNIQUE` (`tipo`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPRESSED;

CREATE TABLE `usuario` (
  `idUsuario` int(11) NOT NULL AUTO_INCREMENT,
  `Empleado_idEmpleado` int(11) NOT NULL,
  `idtipousuario` int(11) NOT NULL,
  `nombre_usuario` varchar(45) NOT NULL,
  `password` varchar(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE KEY `nombre_usuario` (`nombre_usuario`),
  KEY `empleado_usuario_idx` (`Empleado_idEmpleado`),
  KEY `tipousuario_usuario_idx` (`idtipousuario`),
  CONSTRAINT `empleado_usuario` FOREIGN KEY (`Empleado_idEmpleado`) REFERENCES `empleado` (`idEmpleado`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tipousuario_usuario` FOREIGN KEY (`idtipousuario`) REFERENCES `tipousuario` (`idtipousuario`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
